export const ITEM_CHECKLIST_GRUPO_SECURITY_DEF = {
  readAccess: 'ITEM_CHECKLIST_GRUPO_READ',
  updateAccess: 'ITEM_CHECKLIST_GRUPO_UPDATE',
  createAccess: 'ITEM_CHECKLIST_GRUPO_CREATE',
  deleteAccess: 'ITEM_CHECKLIST_GRUPO_DELETE'
};
