export const CONTACT_LIST_DESUSCRIPTION_SECURITY_DEF = {
  readAccess: 'CONTACT_LIST_DESUSCRIPTION_READ',
  updateAccess: 'CONTACT_LIST_DESUSCRIPTION_UPDATE',
  createAccess: 'CONTACT_LIST_DESUSCRIPTION_CREATE',
  deleteAccess: 'CONTACT_LIST_DESUSCRIPTION_DELETE'
};
