export const SEGURIDAD_GRUPO_PERMISO_SECURITY_DEF = {
  readAccess: 'SEGURIDAD_GRUPO_PERMISO_READ',
  updateAccess: 'SEGURIDAD_GRUPO_PERMISO_UPDATE',
  createAccess: 'SEGURIDAD_GRUPO_PERMISO_CREATE',
  deleteAccess: 'SEGURIDAD_GRUPO_PERMISO_DELETE'
};
