export const FICHADO_PROCESAMIENTO_SECURITY_DEF = {
    readAccess: 'FICHADO_PROCESAMIENTO_READ',
    updateAccess: 'FICHADO_PROCESAMIENTO_UPDATE',
    createAccess: 'FICHADO_PROCESAMIENTO_CREATE',
    deleteAccess: 'FICHADO_PROCESAMIENTO_DELETE'
};