export const FORMULARIO_HISTORY_SECURITY_DEF = {
  readAccess: 'FORMULARIO_HISTORY_READ',
  updateAccess: 'FORMULARIO_HISTORY_UPDATE',
  createAccess: 'FORMULARIO_HISTORY_CREATE',
  deleteAccess: 'FORMULARIO_HISTORY_DELETE'
};
