export const PERFIL_IDENTIFICACION_SECURITY_DEF = {
  readAccess: 'PERFIL_IDENTIFICACION_READ',
  updateAccess: 'PERFIL_IDENTIFICACION_UPDATE',
  createAccess: 'PERFIL_IDENTIFICACION_CREATE',
  deleteAccess: 'PERFIL_IDENTIFICACION_DELETE'
};
