export const SEGURIDAD_GRUPO_USUARIO_SECURITY_DEF = {
  readAccess: 'SEGURIDAD_GRUPO_USUARIO_READ',
  updateAccess: 'SEGURIDAD_GRUPO_USUARIO_UPDATE',
  createAccess: 'SEGURIDAD_GRUPO_USUARIO_CREATE',
  deleteAccess: 'SEGURIDAD_GRUPO_USUARIO_DELETE'
};
