export const GRUPOS_TIPO_ACTIVIDAD_SECURITY_DEF = {
  readAccess: 'GRUPOS_TIPO_ACTIVIDAD_READ',
  updateAccess: 'GRUPOS_TIPO_ACTIVIDAD_UPDATE',
  createAccess: 'GRUPOS_TIPO_ACTIVIDAD_CREATE',
  deleteAccess: 'GRUPOS_TIPO_ACTIVIDAD_DELETE'
};
