export const REPORTE_HORAS_MAQUINA_SECURITY_DEF = {
  readAccess: 'REPORTE_HORAS_MAQUINA_READ',
  updateAccess: 'REPORTE_HORAS_MAQUINA_UPDATE',
  createAccess: 'REPORTE_HORAS_MAQUINA_CREATE',
  deleteAccess: 'REPORTE_HORAS_MAQUINA_DELETE'
};
