export const PERFIL_CUENTA_CORRIENTE_SECURITY_DEF = {
    readAccess: 'PERFIL_CUENTA_CORRIENTE_READ',
    updateAccess: 'PERFIL_CUENTA_CORRIENTE_UPDATE',
    createAccess: 'PERFIL_CUENTA_CORRIENTE_CREATE',
    deleteAccess: 'PERFIL_CUENTA_CORRIENTE_DELETE'
};