export const CONTACT_LIST_MEMBERS_SECURITY_DEF = {
  readAccess: 'CONTACT_LIST_MEMBERS_READ',
  updateAccess: 'CONTACT_LIST_MEMBERS_UPDATE',
  createAccess: 'CONTACT_LIST_MEMBERS_CREATE',
  deleteAccess: 'CONTACT_LIST_MEMBERS_DELETE'
};
