export const MATRICULADO_ESTADO_SECURITY_DEF = {
  readAccess: 'MATRICULADO_ESTADO_READ',
  updateAccess: 'MATRICULADO_ESTADO_UPDATE',
  createAccess: 'MATRICULADO_ESTADO_CREATE',
  deleteAccess: 'MATRICULADO_ESTADO_DELETE'
};
