export const IDENTIFICACION_BUSQUEDA_SECURITY_DEF = {
  readAccess: 'IDENTIFICACION_BUSQUEDA_READ',
  updateAccess: 'IDENTIFICACION_BUSQUEDA_UPDATE',
  createAccess: 'IDENTIFICACION_BUSQUEDA_CREATE',
  deleteAccess: 'IDENTIFICACION_BUSQUEDA_DELETE'
};
