export const CERTIFICADO_MATRICULADO_SECURITY_DEF = {
  readAccess: 'CERTIFICADO_MATRICULADO_READ',
  updateAccess: 'CERTIFICADO_MATRICULADO_UPDATE',
  createAccess: 'CERTIFICADO_MATRICULADO_CREATE',
  deleteAccess: 'CERTIFICADO_MATRICULADO_DELETE'
};
